name: homl3
channels:
  - conda-forge
  - defaults
dependencies:
  - python-graphviz  # used only in chapter 6 for dot files
  - ipython=8.17  # a powerful Python shell
  - ipywidgets=8.1  # optionally used only in chapter 12 for tqdm in Jupyter
  - jupyter  # to edit and run Jupyter notebooks
  - matplotlib=3.8  # beautiful plots. See tutorial tools_matplotlib.ipynb
  - nbdime=4.0.1  # optional tool to diff Jupyter notebooks
  - numpy=1.26  # Powerful n-dimensional arrays and numerical computing tools
  - pandas=2.1  # data analysis and manipulation tool
  - pillow=10.1  # image manipulation library, (used by matplotlib.image.imread)
  - pip  # Python's package-management system
  - python=3.10  # your beloved programming language! :)
  - scikit-learn=1.3  # machine learning library
  - scipy=1.11  # scientific/technical computing library
  - tornado>=6.2.0
  - tqdm=4.66  # used only in chapter 12 to display nice progress bars
  - wheel  # built-package format for pip
  - widgetsnbextension=4.0  # interactive HTML widgets for Jupyter notebooks
